# Generated by Django 5.1.6 on 2025-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(default=112, max_length=255),
            preserve_default=False,
        ),
    ]
